# Generated by Django 3.2.7 on 2022-02-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
