# Generated by Django 4.0.3 on 2022-08-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='notes',
            new_name='description',
        ),
        migrations.AddField(
            model_name='lead',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
