# Generated by Django 4.0.3 on 2022-08-29 17:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_rename_notes_lead_description_lead_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2022, 8, 29, 17, 40, 12, 929412, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
